package com.up_and_running.ch4.client;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 */
@WebService(name = "RandService", targetNamespace = "http://rand2.ch4.up_and_running.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface RandService {

    /**
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "next1", targetNamespace = "http://rand2.ch4.up_and_running.com/", className = "com.up_and_running.ch4.client.Next1")
    @ResponseWrapper(localName = "next1Response",
                     targetNamespace = "http://rand2.ch4.up_and_running.com/",
                     className = "com.up_and_running.ch4.client.Next1Response")
    @Action(input = "http://rand2.ch4.up_and_running.com/RandService/next1Request", output = "http://rand2.ch4.up_and_running.com/RandService/next1Response")
    public int next1();


    /**
     * @param arg0
     * @return returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nextN", targetNamespace = "http://rand2.ch4.up_and_running.com/", className = "com.up_and_running.ch4.client.NextN")
    @ResponseWrapper(localName = "nextNResponse",
                     targetNamespace = "http://rand2.ch4.up_and_running.com/",
                     className = "com.up_and_running.ch4.client.NextNResponse")
    @Action(input = "http://rand2.ch4.up_and_running.com/RandService/nextNRequest", output = "http://rand2.ch4.up_and_running.com/RandService/nextNResponse")
    public List<Integer> nextN(@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
